# html lang
language: en

# main menu navigation
menu:
  Home: /
  Categories: /categories
  Tags: /tags
  Archives: /archives
  About: /about

# customize your terminal panel
terminal:
  #Home
  Blog:
     purpose:
       typ: string
       val:  I am born penniless,but must not be still poor and frustrated at the time of death.
     author:
       typ: string
       val: Three Zhang
#     more:
#       typ: link
#       val: check here
#       url: https://github.com/lazysheep666/lazysheep666.github.io
  #About
  "Author":
     name:
       typ: string
       val: Three Zhang
     gender:
       typ: string
       val: Male
     locations:
       typ: string
       val: Shanghai, China
     email:
       typ: string
       val: 0b00000011.com@gmail.com
#     github:
#       typ: link
#       val: github.com/three-zhang
#       url: https://github.com/three-zhang
  #Categories
  Categories:
  #Tags
  Tags:
  #Archives
  Archives:
  #Post
  Post:

#social media
#name: url
social:
   github: https://github.com/three-zhang
  # weibo: https://weibo.com/u/5318061001
  
# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/nav.js
- /js/scroll.js
- /js/index.js
# the third-party loaded in the head
third_party:
  js:
    jquery: /js/third-party/jquery.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 
  css:
    font-awsome: https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css